"""empty message

Revision ID: 35319ec29cdd
Revises: a4ebff2d417f
Create Date: 2020-05-23 22:45:07.473505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35319ec29cdd'
down_revision = 'a4ebff2d417f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    # ### end Alembic commands ###
